const apiUrl = 'https://drmtest.sparklog.com/app/'//'http://192.168.2.236:3000/app/'

export const signIn = apiUrl + 'session'
export const getInfo = apiUrl + 'user'
export const updateInfo = apiUrl + 'user/update'
export const updatePassword = apiUrl + 'user/update/password'
export const getNews = apiUrl + 'news'
export const getNewsOne = apiUrl + 'news/one'
export const getBugs = apiUrl + 'bugs'
export const getBug = apiUrl + 'bugs/one'
export const getCate = apiUrl + 'bugs/cate'
export const getBugsHot = apiUrl + 'bugs/hots'
export const postNewOrder = apiUrl + 'order/new'
export const getDeviceAddress = apiUrl + 'devices/address'
export const getDevices = apiUrl + 'devices'
export const getDevicesSearch = apiUrl + 'devices/search'
export const getDevicesHots = apiUrl + 'devices/hots'
export const getDevice = apiUrl + 'devices/one'
export const postDeviceRemark = apiUrl + 'devices/one/remark'
export const postDeviceTimelines = apiUrl + 'devices/one/timelines'
export const postDeviceImages = apiUrl + 'devices/one/images'
export const getNotices = apiUrl + 'notices'
export const getNoticesOne = apiUrl + 'notices/one'
export const setAllNoticesRead = apiUrl + 'notices/all/read'
export const setOneNoticesRead = apiUrl + 'notices/one/read'
export const getOrderOne = apiUrl + 'order/one'
export const setOrderSolved = apiUrl + 'order/solved'
export const getMoniterdevs = apiUrl + 'moniterdevs'
export const getMoniterdevsSearch = apiUrl + 'moniterdevs/search'
export const getDeviceCcsort = apiUrl + 'devices/ccsort'
export const getDevicePresort = apiUrl + 'devices/presort'
export const getDeviceFuelsort = apiUrl + 'devices/fuelsort'
export const getMoniterdevsNum = apiUrl + 'moniterdevs/number'
export const getMoniterdevsNumField = apiUrl + 'moniterdevs/number/field'
export const postOrderUpload = apiUrl + 'order/upload'
export const postOrderDelimg = apiUrl + 'order/delimg'
export const getPartSearch = apiUrl + 'parts/search'
export const getPartHots = apiUrl + 'parts/hots'
export const getPartFirst = apiUrl + 'parts/first'
export const getPartSecond = apiUrl + 'parts/second'
export const getPartOne = apiUrl + 'parts/one'
export const postFindpass = apiUrl + 'findpass'
export const postCheckcode = apiUrl + 'checkcode'
export const postResetpass = apiUrl + 'resetpass'




