const apiUrl = 'https://api.wardenger.me/app/'//'http://192.168.2.236:3000/app/'

export const signIn = apiUrl + 'session'
export const getInfo = apiUrl + 'user'
export const updateInfo = apiUrl + 'user/update'
export const updatePassword = apiUrl + 'user/update/password'
export const getNews = apiUrl + 'news'
export const getNewsOne = apiUrl + 'news/one'
export const getBugs = apiUrl + 'bugs'
export const getBug = apiUrl + 'bugs/one'
export const getCate = apiUrl + 'bugs/cate'
export const getBugsHot = apiUrl + 'bugs/hots'
export const postNewOrder = apiUrl + 'order/new'
export const getDeviceAddress = apiUrl + 'devices/address'
export const getDevices = apiUrl + 'devices'
export const getDevice = apiUrl + 'devices/one'
export const postDeviceRemark = apiUrl + 'devices/one/remark'
export const postDeviceTimelines = apiUrl + 'devices/one/timelines'
export const postDeviceImages = apiUrl + 'devices/one/images'
export const getNotices = apiUrl + 'notices'
export const getNoticesOne = apiUrl + 'notices/one'
export const setAllNoticesRead = apiUrl + 'notices/all/read'
export const setOneNoticesRead = apiUrl + 'notices/one/read'
export const setOrderSolved = apiUrl + 'order/solved'

