export const drmOne = '多元热流体设备'
export const drmTwo = '信息及用户管理系统'
export const drmThree = 'MMHFD'
export const homeLabel = '首页'
export const deviceLabel = '设备档案'
export const statusLabel = '状态监控'
export const diagnoseLabel = '故障诊断'
export const seekLabel = '配件检索'

export const loginInputEmail = '请输入邮箱'
export const loginInputWord = '请输入密码'
export const loginText = '登录'
export const loginForgetWord = '忘记密码?'
export const basicDocument = '基本资料'
export const userName = '用户名'
export const companyName = '公司名称'
export const phoneNumber = '联系电话'
export const postalAddress = '通讯地址'
export const securitySetting = '安全设置'
export const resetPassword = '修改密码'
export const personalInformation = '个人信息'
export const save = '保存'
export const online = '正常工作中'
export const offline = '设备已离线。请检查通讯设备。'
export const onToOffText = '最后一次成功连接的时间是'
export const onState = '在线'
export const offState = '离线'
export const equipmentName = '设备名'
export const equipmentRunState = '运行状态'
export const equipmentRunImg = '运行图示（点击图片放大）'
export const equipmentIndexData = '指标数据'
export const indexDataUpdateTime = '更新时间: '
export const equipmentRunningLog = '运行日志'


